# Generated by Django 4.1.7 on 2023-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='img/default_image.jpg', max_length=25, verbose_name='item image'),
        ),
    ]
